services:
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: healthcore_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  app:
    build: .

    volumes:
      - .:/app:z
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    environment:
      - BUILD_ENVIRONMENT=false
    depends_on:
      - db
      - redis

  celery_worker:
    build: .
    command: celery -A healthcore worker --loglevel=info
    volumes:
      - .:/app:z
    env_file:
      - ./.env
    environment:
      - BUILD_ENVIRONMENT=false
    depends_on:
      - db
      - redis

  celery_beat:
    build: .
    command: celery -A healthcore beat --loglevel=info
    volumes:
      - .:/app:z
    env_file:
      - ./.env
    environment:
      - BUILD_ENVIRONMENT=false
    depends_on:
      - db
      - redis

volumes:
  postgres_data: